export const projects = [
    {
        name: " AIsthetica",
        client: "Grow",
        description: "AI Art Generation",
        src: "1.png",
        year: 2024,
    },
    {
        name: "Code Clash",
        client: "Decimal",
        description: "Competetive Coding",
        src: "2.png",
        year: 2024,
    },
    {
        name: "Technical Quiz",
        client: "analogueagency",
        description: "Quiz Based on Tech",
        src: "3.png",
        year: 2024,
    },
    {
        name: "Bytes Of Knowledge",
        client: "Wix Playground",
        description: "Tech Talk",
        src: "4.png",
        year: 2024,
    },
    {
        name: "Cipher Challenge",
        client: "POWELL—STUDIO",
        description: "Code Debugging",
        src: "5.png",
        year: 2024,
    },
    {
        name: "Break The Query",
        client: "ET Studio",
        description: "SQL Challenge",
        src: "6.png",
        year: 2024,
    },
    {
        name: "Hackathon",
        client: "Ingamana",
        description: "AI Themed Hackathon",
        src: "7.png",
        year: 2024,
    },
    {
        name: "Code Red",
        client: "Shader Studio",
        description: "Debate",
        src: "8.png",
        year: 2024,
    },
    {
        name: "Web Craft",
        client: "Shader Studio",
        description: "Frontend Challenge",
        src: "9.png",
        year: 2024,
    },
    {
        name: "Treasure Hunt",
        client: "Shader Studio",
        description: "Riddle Based Treasure Hunt",
        src: "10.png",
        year: 2024,
    },
    {
        name: "Spell Bee",
        client: "Shader Studio",
        description: "Spelling Contest",
        src: "11.png",
        year: 2020,
    },
    {
        name: "The Click Chronicles",
        client: "Shader Studio",
        description: "Photography Challenge",
        src: "12.png",
        year: 2024,
    },
    {
        name: "Esports",
        client: "Shader Studio",
        description: "VALORANT | BGMI | FREE FIRE",
        src: "13.png",
        year: 2024,
    },
    {
        name: "Key Clash",
        client: "Shader Studio",
        description: "Typing Contest",
        src: "14.png",
        year: 2024,
    }
]
